# Configuration Welcome to the Jungle - Hu Chenwei
# Graphiste / Illustratrice / Brand Designer

welcome_to_the_jungle_username: ""
welcome_to_the_jungle_password: ""

job_keyword_list:
  - "alternance graphiste"
  - "alternance graphisme"
  - "alternance design graphique"
  - "alternance illustrateur"
  - "alternance illustration"
  - "alternance branding"
  - "alternance identité visuelle"
  - "alternance direction artistique"
  - "alternance PAO"
  - "alternance création graphique"
  - "alternance studio créatif"
  - "alternance design studio"
  - "alternance agence design"
  - "stage graphiste"
  - "stage illustrateur"

is_internship: True
sort_by_date: True
number_of_page_to_search: 5
maximum_number_of_offer: 30

where_is_the_job:
  - "Paris"
country_of_the_job: "Île-de-France"

forbiden_words_job_offer_name:
  - "DevOps"
  - "développeur"
  - "data"
  - "commercial"
  - "vendeur"
  - "comptable"
  - "ingenieur"
  - "technicien"
  - "senior"
  - "lead"

forbiden_words_job_offer_question:
  - "DevOps"
  - "développement"

current_post: "Graphiste & Illustratrice"
language: "french"
covert_letter_lenght: "court"
skip_question: False
skip_cover_letter: False
print_error: False
send_discord: False
apply: True
apply_to_offer_who_have_job_keyword_list_element_in_their_name: True
print_cover_letter: False
